### ISSUE TITLE
Finalize Add Users To Tour

### ISSUE THREAD

**Issue by tashiad** [Back-Country-Buddy/backcountry-buddy-UI#105]
- [x] api/ui error handling
- [x]  user that was added to tour (that is not the tour creator) should be able to see that tour in their current tours and be able to edit/add to it.

**Comment by deadbelly** [comment]
We had previously ran into a bug where users added to a tour they did not create, would not see that tour under their current tours tab. As of today that bug cannot be recreated (correct me if I'm wrong). Can this issue be closed, or do we want to revamp any of the ui or error handling before we call this finished?

**Comment by tashiad** [comment]
I'm assuming you and Liam tested this out by adding each other? If so it's probably good to go, but I think we should at least fix the `nil`s and finalize error handling (like if someone tries to add a user that doesn't exist) before closing the issue: <img width="239" alt="Screen Shot 2021-05-02 at 2 38 12 PM" src="https://user-images.githubusercontent.com/66852774/116827927-f4f37600-ab58-11eb-9888-8d1b2631b958.png">
