### ISSUE TITLE
Some users unable to log in

### ISSUE THREAD

**Issue by tashiad** [Back-Country-Buddy/backcountry-buddy-UI#111]

**Comment by deadbelly** [comment]
Liam and I can no longer re-create this issue. Steps we've tried:
```
1) Create a new email address
2) Click "sign up" on the login screen
3) Authorize access
```
and
```
1) Create a new email address
2) Click "sign in with google" on the login screen
3) Authorize access
```

Before working on this we made sure to unregister the browser's service worker and reload, just in case bugged info from a previous build was cached somewhere. This doesn't seem like a likely culprit given the context of the bug earlier this week. The possibility of some accounts that were created during a certain build being bugged seems unlikely but we can't completely rule it out.

Can anyone recreate the bug? If so please please document it as thoroughly as possible, and post re-creation steps as well as screenshots of your console, and network logs. If not we should close this issue.

**Comment by tashiad** [comment]
Thanks for outlining all of this! I know that Alex was previously unable to log in and my partner Peter couldn't either. I'll look into if they're able to log in now before we close the issue.

**Comment by tashiad** [comment]
An update here: I played around on Peter's Android / Google account. He's able to successfully login (so the Auth0 API is working) but anything that involves our own APIs sends him to the 404 page, so the app is basically unusable for him. Name is  Peter Iwaoka for further troubleshooting...
